#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel...
$app = require_once __DIR__.'/bootstrap/app.php';

// Run the console application...
$status = $app->handleCommand(new Symfony\Component\Console\Input\ArgvInput);

// Exit with the command's status...
exit($status);
